general:
  app_name: pyspark_k8s_boilerplate
  sample_configs: [1, 2, 3, 4]
  interactive_time_limit: 86400
  log_bucket: gs://spark-logging-test/logs/
data:
  object_bucket: scratch_bucket
  database: BigQueryDev
  pi_partitions: 4
  titanic_root: gs://albell-test/
model:
  cv_strategy: time-series
  imputation: zero
  selection: RFE
  exclude_features: [A, B, C, D]

